# Generated by Django 3.2.8 on 2021-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='country',
            field=models.CharField(choices=[('AFG', 'Afghanistan'), ('AUS', 'Australia'), ('BRA', 'Brazil'), ('CHN', 'China'), ('FRA', 'France')], default='AFG', max_length=3),
        ),
    ]
